### PR TITLE
Surport adb reboot fastboot/recovery feature

### PR DESCRIPTION
**Pull request by xiaopingx**
Add bootonce-fastboot and bootonce-recovery strings
selections along with bootone-bootloader.

Bug ID: https://jira01.devtools.intel.com/browse/OAM-43555
Test: Test it on Joule board, fastboot/recovery varibles
could be saved in misc partition.

Signed-off-by: hu,xiaopingx <xiaopingx.hu@intel.com>
Signed-off-by: Chen,Xihua <xihua.chen@intel.com>

### CODE REVIEW

**Comment by xiaopingx** [comment]
https://github.com/android-ia/bootable-recovery/pull/3

**Comment by xiaopingx** [comment]
For now, the EFI variable couldn't work well now, but we should support get into recovery mode, when we solve the EFI variable and we can revert them in recovery repository. thanks

**Comment by kalyankondapally** [comment]
do we need this  https://github.com/android-ia/system-core/pull/3 ?

**Comment by kalyankondapally** [comment]
@Kishore409 to check on joule

**Comment by xihua-chen** [comment]
hold on this patch first, some patches in recovery related with drm

**Comment by Kishore409** [comment]
@xiaopingx @xihua-chen , any update on this

**Comment by xiaopingx** [comment]
Please hold on, I am trying to get another patches that relative

**Comment by sgnanase** [comment]
Merged...

**Pull request merged**
